spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/spicehub}
    username: ${DB_USERNAME:spicehub}
    password: ${DB_PASSWORD:spicehub}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6382}

  security:
    refresh-cookie:
      secure: false

  jpa:
    show-sql: true