spring:
  application:
    name: spicehub-marketplace

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    issuer: spicehub
    access-token-ttl: 60m
    secret: ${JWT_SECRET:c3BpY2VodWItZGV2LWp3dC1zZWNyZXQta2V5LTMyYiE=}

server:
  port: ${SERVER_PORT:8080}